-- MySQL Script generated by MySQL Workbench
-- Wed Feb  5 15:00:07 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sjakkarena
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS sjakkarena ;

-- -----------------------------------------------------
-- Schema sjakkarena
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS sjakkarena DEFAULT CHARACTER SET utf8 ;
USE sjakkarena ;

-- -----------------------------------------------------
-- Table `sjakkarena`.`game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS sjakkarena.`game` ;

CREATE TABLE IF NOT EXISTS sjakkarena.`game`(
  `game_id` INT NOT NULL AUTO_INCREMENT,
  `table` TINYINT UNSIGNED NULL,
  `start` TIME NULL,
  `end` TIME NULL,
  `white` INT NOT NULL,
  `black` INT NOT NULL,
  `result` VARCHAR(3) NULL,
  PRIMARY KEY (`game_id`),
  INDEX `fk_game_white_idx` (`white` ASC) VISIBLE,
  INDEX `fk_game_black_idx` (`black` ASC) VISIBLE,
  CONSTRAINT `fk_game_white`
    FOREIGN KEY (`white`)
    REFERENCES sjakkarena.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_black`
    FOREIGN KEY (`black`)
    REFERENCES sjakkarena.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjakkarena`.`tournament`
-- -----------------------------------------------------
DROP TABLE IF EXISTS sjakkarena.`tournament` ;

CREATE TABLE IF NOT EXISTS sjakkarena.`tournament`(
  `tournament_id` VARCHAR(255),
  `tournament_name` VARCHAR(255),
  `admin_email` VARCHAR(255),
  `start` TIME NULL,
  `end` TIME NULL,
  `tables` TINYINT UNSIGNED NULL,
  `max_rounds` SMALLINT UNSIGNED NULL,
  `active` TINYINT(1),
  PRIMARY KEY (`tournament_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjakkarena`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS sjakkarena.`user` ;

CREATE TABLE IF NOT EXISTS sjakkarena.`user`(
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `active` TINYINT(1) UNSIGNED NULL,
  `points` DECIMAL(1,1) UNSIGNED NULL,
  `rounds` SMALLINT UNSIGNED NULL,
  `tournament` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `Id_UNIQUE` (`user_id` ASC) VISIBLE,
  INDEX `fk_user_tournament_idx` (`tournament` ASC) VISIBLE,
  CONSTRAINT `fk_user_tournament`
    FOREIGN KEY (`tournament`)
    REFERENCES sjakkarena.`tournament` (`tournament_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
