-- MySQL Script generated by MySQL Workbench
-- Wed Feb  5 15:00:07 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sjakkarena
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS sjakkarena ;

-- -----------------------------------------------------
-- Schema sjakkarena
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS sjakkarena DEFAULT CHARACTER SET utf8 ;
USE sjakkarena ;

-- -----------------------------------------------------
-- Table `sjakkarena`.`Result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS sjakkarena.`Result` ;

CREATE TABLE IF NOT EXISTS sjakkarena.`Result`(
  `points` DECIMAL(1,1) UNSIGNED NULL,
  `Round_Id` INT NOT NULL,
  `Round_Tournament_idTournament` INT NOT NULL,
  `Round_User_Id` INT NOT NULL,
  PRIMARY KEY (`Round_Id`, `Round_Tournament_idTournament`, `Round_User_Id`),
  CONSTRAINT `fk_Result_Round1`
    FOREIGN KEY (`Round_Id` , `Round_Tournament_idTournament` , `Round_User_Id`)
    REFERENCES sjakkarena.`Round` (`Id` , `Tournament_idTournament` , `User_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjakkarena`.`Round`
-- -----------------------------------------------------
DROP TABLE IF EXISTS sjakkarena.`Round` ;

CREATE TABLE IF NOT EXISTS sjakkarena.`Round`(
  `Id` INT NOT NULL AUTO_INCREMENT,
  `table` TINYINT UNSIGNED NULL,
  `start` TIME NULL,
  `end` TIME NULL,
  `Tournament_idTournament` INT NOT NULL,
  `User_Id` INT NOT NULL,
  `User_Id1` INT NOT NULL,
  PRIMARY KEY (`Id`, `Tournament_idTournament`, `User_Id`, `User_Id1`),
  INDEX `fk_Round_Tournament1_idx` (`Tournament_idTournament` ASC) VISIBLE,
  INDEX `fk_Round_User1_idx` (`User_Id` ASC) VISIBLE,
  INDEX `fk_Round_User2_idx` (`User_Id1` ASC) VISIBLE,
  CONSTRAINT `fk_Round_Tournament1`
    FOREIGN KEY (`Tournament_idTournament`)
    REFERENCES sjakkarena.`Tournament` (`idTournament`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Round_User1`
    FOREIGN KEY (`User_Id`)
    REFERENCES sjakkarena.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Round_User2`
    FOREIGN KEY (`User_Id1`)
    REFERENCES sjakkarena.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjakkarena`.`Tournament`
-- -----------------------------------------------------
DROP TABLE IF EXISTS sjakkarena.`Tournament` ;

CREATE TABLE IF NOT EXISTS sjakkarena.`Tournament`(
  `idTournament` INT NOT NULL,
  `start` TIME NULL,
  `end` TIME NULL,
  `tables` TINYINT UNSIGNED NULL,
  `max_rounds` SMALLINT UNSIGNED NULL,
  `pause_length` TIME NULL,
  `admin_uuid` INT UNSIGNED NULL,
  PRIMARY KEY (`idTournament`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjakkarena`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS sjakkarena.`User` ;

CREATE TABLE IF NOT EXISTS sjakkarena.`User`(
  `Id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `pause` TINYINT(1) UNSIGNED NULL,
  `active` TINYINT(1) UNSIGNED NULL,
  `points` DECIMAL(1,1) UNSIGNED NULL,
  `rounds` SMALLINT UNSIGNED NULL,
  `Tournament_idTournament` INT NOT NULL,
  PRIMARY KEY (`Id`, `Tournament_idTournament`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  INDEX `fk_User_Tournament1_idx` (`Tournament_idTournament` ASC) VISIBLE,
  CONSTRAINT `fk_User_Tournament1`
    FOREIGN KEY (`Tournament_idTournament`)
    REFERENCES sjakkarena.`Tournament` (`idTournament`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
