-- MySQL Script generated by MySQL Workbench
-- Wed Feb  5 15:00:07 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sjakkarena
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS sjakkarena ;

-- -----------------------------------------------------
-- Schema sjakkarena
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS sjakkarena DEFAULT CHARACTER SET utf8 ;
USE sjakkarena ;

-- -----------------------------------------------------
-- Table `sjakkarena`.`game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS sjakkarena.`game` ;

CREATE TABLE IF NOT EXISTS sjakkarena.`game`(
  `game_id` INT NOT NULL AUTO_INCREMENT,
  `table` TINYINT UNSIGNED NULL,
  `start` DATETIME NULL,
  `end` DATETIME NULL,
  `white_player` INT NOT NULL,
  `black_player` INT NOT NULL,
  `result` VARCHAR(7) NULL,
  `active` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`game_id`),
  INDEX `fk_game_white_idx` (`white_player` ASC) VISIBLE,
  INDEX `fk_game_black_idx` (`black_player` ASC) VISIBLE,
  CONSTRAINT `fk_game_white`
    FOREIGN KEY (`white_player`)
    REFERENCES sjakkarena.`player` (`player_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_black`
    FOREIGN KEY (`black_player`)
    REFERENCES sjakkarena.`player` (`player_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjakkarena`.`tournament`
-- -----------------------------------------------------
DROP TABLE IF EXISTS sjakkarena.`tournament` ;

CREATE TABLE IF NOT EXISTS sjakkarena.`tournament`(
  `tournament_id` INT NOT NULL,
  `tournament_name` VARCHAR(255),
  `admin_email` VARCHAR(255),
  `start` DATETIME NULL,
  `end` DATETIME NULL,
  `tables` TINYINT UNSIGNED NULL,
  `max_rounds` SMALLINT UNSIGNED NULL,
  `active` TINYINT(1) DEFAULT 1,
  `admin_uuid` VARCHAR(255) NULL UNIQUE,
  `early_start` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`tournament_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sjakkarena`.`player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sjakkarena`.`player` ;

CREATE TABLE IF NOT EXISTS `sjakkarena`.`player`(
  `player_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `in_tournament` TINYINT(1) UNSIGNED DEFAULT 1,
  `paused` TINYINT(1) UNSIGNED DEFAULT 0,
  `points` DECIMAL(5,1) UNSIGNED NULL DEFAULT 0,
  `rounds` SMALLINT UNSIGNED NULL DEFAULT 0,
  `tournament` INT NOT NULL,
  `icon` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`player_id`),
  UNIQUE INDEX `Id_UNIQUE` (`player_id` ASC) VISIBLE,
  UNIQUE KEY `name_tournament` (`name`, `tournament`),
  INDEX `fk_user_tournament_idx` (`tournament` ASC) VISIBLE,
  CONSTRAINT `fk_user_tournament`
    FOREIGN KEY (`tournament`)
    REFERENCES sjakkarena.`tournament` (`tournament_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
